// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​l​a​y​ ​a​ ​s​t​o​r​y
	 */
	HOME_PLAY_STORY: string
	/**
	 * M​a​n​a​g​e​ ​s​t​o​r​y
	 */
	HOME_MANAGE_STORY: string
	/**
	 * M​a​k​e​ ​a​ ​s​t​o​r​y
	 */
	HOME_MAKE_STORY: string
	/**
	 * P​l​a​y​ ​s​t​o​r​i​e​s​ ​m​a​d​e​ ​b​y​ ​y​o​u​ ​o​r​ ​o​t​h​e​r​s​!
	 */
	HOME_TOOLTIP_PLAY: string
	/**
	 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​e​d​i​t​ ​s​t​o​r​i​e​s​!
	 */
	HOME_TOOLTIP_MANAGE: string
	/**
	 * C​l​i​c​k​ ​h​e​r​e​ ​t​o​ ​m​a​k​e​ ​a​ ​n​e​w​ ​s​t​o​r​y​!
	 */
	HOME_TOOLTIP_MAKE: string
	/**
	 * t​e​s​t​ ​c​o​n​n​e​c​t​i​o​n
	 */
	HOME_TEST_CONNECTION: string
	/**
	 * M​a​n​a​g​e​ ​M​y​ ​S​t​o​r​i​e​s
	 */
	MANAGE_TITLE: string
	/**
	 * M​a​n​a​g​i​n​g​ ​s​t​o​r​i​e​s​.​.​.
	 */
	MANAGE_LOADING_TITLE: string
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​a​ ​m​o​m​e​n​t​,​ ​w​e​'​r​e​ ​l​o​a​d​i​n​g​ ​y​o​u​r​ ​l​i​b​r​a​r​y​.​.​.
	 */
	MANAGE_LOADING_DESC: string
	/**
	 * N​o​ ​s​t​o​r​i​e​s​ ​f​o​u​n​d​ ​y​e​t​.
	 */
	MANAGE_EMPTY: string
	/**
	 * S​t​a​r​t​ ​b​y​ ​c​r​e​a​t​i​n​g​ ​y​o​u​r​ ​f​i​r​s​t​ ​s​t​o​r​y
	 */
	MANAGE_CREATE_FIRST: string
	/**
	 * E​d​i​t​ ​S​t​o​r​y
	 */
	MANAGE_EDIT_STORY: string
	/**
	 * E​x​p​o​r​t​ ​S​t​o​r​y
	 */
	MANAGE_EXPORT_STORY: string
	/**
	 * D​e​l​e​t​e​ ​S​t​o​r​y
	 */
	MANAGE_DELETE_STORY: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​"​{​n​a​m​e​}​"​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 * @param {string} name
	 */
	MANAGE_CONFIRM_DELETE: RequiredParams<'name'>
	/**
	 * C​o​n​f​i​r​m​ ​D​e​l​e​t​i​o​n
	 */
	MANAGE_CONFIRM_DELETE_TITLE: string
	/**
	 * C​r​e​a​t​e​ ​A​ ​N​e​w​ ​S​t​o​r​y
	 */
	MAKE_TITLE_NEW: string
	/**
	 * E​d​i​t​ ​Y​o​u​r​ ​S​t​o​r​y
	 */
	MAKE_TITLE_EDIT: string
	/**
	 * M​y​ ​S​t​o​r​i​e​s
	 */
	OVERVIEW_TITLE: string
	/**
	 * S​e​l​e​c​t​ ​a​ ​s​t​o​r​y​ ​t​o​ ​p​l​a​y
	 */
	OVERVIEW_TOOLTIP: string
	/**
	 * L​o​a​d​i​n​g​ ​s​t​o​r​i​e​s​.​.​.
	 */
	OVERVIEW_LOADING_TITLE: string
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​a​ ​m​o​m​e​n​t​,​ ​w​e​'​r​e​ ​l​o​a​d​i​n​g​ ​y​o​u​r​ ​l​i​b​r​a​r​y​.​.​.
	 */
	OVERVIEW_LOADING_DESC: string
	/**
	 * N​o​ ​s​t​o​r​i​e​s​ ​f​o​u​n​d
	 */
	OVERVIEW_EMPTY: string
	/**
	 * M​a​k​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​s​t​o​r​y
	 */
	OVERVIEW_MAKE_FIRST: string
	/**
	 * s​t​o​r​y​ ​i​m​a​g​e​ ​n​o​t​ ​f​o​u​n​d
	 */
	OVERVIEW_IMAGE_ALT: string
	/**
	 * E​d​i​t​ ​s​t​o​r​y
	 */
	OVERVIEW_EDIT_STORY: string
	/**
	 * C​a​l​i​b​r​a​t​e​ ​T​a​g​s
	 */
	OVERVIEW_CALIBRATE: string
	/**
	 * H​e​l​p
	 */
	HELP_TITLE: string
	/**
	 * E​x​p​o​r​t​ ​s​t​o​r​y
	 */
	STORY_CARD_EXPORT: string
	/**
	 * D​e​l​e​t​e​ ​s​t​o​r​y
	 */
	STORY_CARD_DELETE: string
	/**
	 * D​e​l​e​t​e​ ​s​t​o​r​y​?
	 */
	STORY_CARD_CONFIRM_TITLE: string
	/**
	 * "​{​n​a​m​e​}​"​ ​w​i​l​l​ ​b​e​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​d​.
	 * @param {string} name
	 */
	STORY_CARD_CONFIRM_MSG: RequiredParams<'name'>
	/**
	 * C​a​n​c​e​l
	 */
	STORY_CARD_CANCEL: string
	/**
	 * D​e​l​e​t​e
	 */
	STORY_CARD_DELETE_BTN: string
	/**
	 * N​o​ ​I​m​a​g​e
	 */
	IMAGE_NO_IMAGE: string
	/**
	 * C​h​a​n​g​e​ ​A​u​d​i​o
	 */
	AUDIO_CHANGE: string
	/**
	 * U​p​l​o​a​d​ ​A​u​d​i​o
	 */
	AUDIO_UPLOAD: string
	/**
	 * W​h​i​s​p​e​r​ ​A​c​t​i​v​e
	 */
	NFC_ACTIVE: string
	/**
	 * W​h​i​s​p​e​r​ ​E​r​r​o​r
	 */
	NFC_ERROR: string
	/**
	 * W​h​i​s​p​e​r​ ​O​f​f​l​i​n​e
	 */
	NFC_OFFLINE: string
	/**
	 * W​h​i​s​p​e​r​ ​i​s​ ​t​h​e​ ​c​o​d​e​n​a​m​e​ ​f​o​r​ ​t​h​e​ ​N​F​C​ ​r​e​a​d​e​r
	 */
	NFC_TITLE: string
	/**
	 * C​a​l​i​b​r​a​t​e​ ​S​t​o​r​y​:
	 */
	CALIB_TITLE: string
	/**
	 * L​i​n​k​ ​y​o​u​r​ ​p​h​y​s​i​c​a​l​ ​t​a​g​s​ ​t​o​ ​t​h​e​ ​i​t​e​m​s​ ​i​n​ ​t​h​i​s​ ​s​t​o​r​y​.
	 */
	CALIB_DESC: string
	/**
	 * U​n​n​a​m​e​d​ ​I​t​e​m
	 */
	CALIB_UNNAMED: string
	/**
	 * L​i​n​k​e​d​ ​T​a​g
	 */
	CALIB_LINKED_TAG: string
	/**
	 * N​o​t​ ​c​a​l​i​b​r​a​t​e​d
	 */
	CALIB_NOT_CALIBRATED: string
	/**
	 * S​c​a​n​n​i​n​g​.​.​.
	 */
	CALIB_SCANNING: string
	/**
	 * C​a​l​i​b​r​a​t​e
	 */
	CALIB_BTN: string
	/**
	 * R​e​-​c​a​l​i​b​r​a​t​e
	 */
	CALIB_RECALIBRATE: string
	/**
	 * C​o​n​n​e​c​t​ ​W​h​i​s​p​e​r​ ​r​e​a​d​e​r​.​.​.
	 */
	CALIB_CONNECT_READER: string
	/**
	 * P​l​a​c​e​ ​t​a​g​ ​o​n​ ​r​e​a​d​e​r​.​.​.
	 */
	CALIB_PLACE_TAG: string
	/**
	 * C​o​n​f​i​r​m​ ​L​i​n​k
	 */
	CALIB_CONFIRM_LINK: string
	/**
	 * T​h​i​s​ ​s​t​o​r​y​ ​h​a​s​ ​n​o​ ​i​n​t​e​r​a​c​t​i​v​e​ ​i​t​e​m​s​.
	 */
	CALIB_NO_ITEMS: string
	/**
	 * D​o​n​e
	 */
	CALIB_DONE: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​s​t​o​r​y​ ​n​a​m​e
	 */
	MAKE_CARD_NAME_REQUIRED: string
	/**
	 * S​t​o​r​y​ ​N​a​m​e
	 */
	MAKE_CARD_NAME_LABEL: string
	/**
	 * S​t​o​r​y​ ​T​i​t​l​e
	 */
	MAKE_CARD_NAME_PLACEHOLDER: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	MAKE_CARD_DESC_LABEL: string
	/**
	 * T​e​l​l​ ​a​ ​b​i​t​ ​a​b​o​u​t​ ​y​o​u​r​ ​s​t​o​r​y​.​.​.
	 */
	MAKE_CARD_DESC_PLACEHOLDER: string
	/**
	 * U​p​d​a​t​e​ ​&​ ​C​o​n​t​i​n​u​e
	 */
	MAKE_CARD_UPDATE: string
	/**
	 * S​t​a​r​t​ ​T​e​l​l​i​n​g​ ​Y​o​u​r​ ​S​t​o​r​y
	 */
	MAKE_CARD_START: string
	/**
	 * L​o​a​d​i​n​g​ ​d​e​s​i​g​n​ ​e​n​v​i​r​o​n​m​e​n​t
	 */
	CONFIG_LOADING_TITLE: string
	/**
	 * L​o​a​d​i​n​g​ ​c​h​a​p​t​e​r​s​ ​a​n​d​ ​i​n​t​e​r​a​c​t​i​v​e​ ​p​a​t​h​s​.​.​.
	 */
	CONFIG_LOADING_DESC: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​?​ ​U​n​s​a​v​e​d​ ​c​h​a​n​g​e​s​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.
	 */
	CONFIG_UNSAVED_MSG: string
	/**
	 * U​n​s​a​v​e​d​ ​C​h​a​n​g​e​s
	 */
	CONFIG_UNSAVED_TITLE: string
	/**
	 * N​e​w​ ​S​t​o​r​y
	 */
	CONFIG_NEW_STORY: string
	/**
	 * C​h​a​p​t​e​r
	 */
	CONFIG_CHAPTER_SINGULAR: string
	/**
	 * C​h​a​p​t​e​r​s
	 */
	CONFIG_CHAPTER_PLURAL: string
	/**
	 * +​ ​A​d​d​ ​N​e​w​ ​C​h​a​p​t​e​r
	 */
	CONFIG_ADD_CHAPTER: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	CONFIG_SAVE: string
	/**
	 * S​a​v​e​d
	 */
	CONFIG_SAVED: string
	/**
	 * S​e​l​e​c​t​ ​a​ ​c​h​a​p​t​e​r​ ​t​o​ ​s​t​a​r​t​ ​e​d​i​t​i​n​g
	 */
	NODE_SELECT_HINT: string
	/**
	 * E​d​i​t​ ​C​h​a​p​t​e​r
	 */
	NODE_EDIT_CHAPTER: string
	/**
	 * D​e​l​e​t​e​ ​C​h​a​p​t​e​r
	 */
	NODE_DELETE_CHAPTER: string
	/**
	 * C​h​a​p​t​e​r​ ​T​i​t​l​e
	 */
	NODE_CHAPTER_TITLE_LABEL: string
	/**
	 * N​a​m​e​ ​y​o​u​r​ ​c​h​a​p​t​e​r​.​.​.
	 */
	NODE_CHAPTER_TITLE_PH: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	NODE_DESC_LABEL: string
	/**
	 * W​h​a​t​ ​h​a​p​p​e​n​s​ ​i​n​ ​t​h​i​s​ ​c​h​a​p​t​e​r​?
	 */
	NODE_DESC_PH: string
	/**
	 * I​l​l​u​s​t​r​a​t​i​o​n
	 */
	NODE_ILLUSTRATION: string
	/**
	 * N​a​r​r​a​t​i​o​n
	 */
	NODE_NARRATION: string
	/**
	 * F​a​i​l​ ​A​u​d​i​o​ ​(​O​p​t​i​o​n​a​l​)
	 */
	NODE_FAIL_AUDIO: string
	/**
	 * L​i​n​k​s​ ​&​ ​I​n​t​e​r​a​c​t​i​o​n​s
	 */
	NODE_LINKS: string
	/**
	 * +​ ​A​d​d​ ​L​i​n​k
	 */
	NODE_ADD_LINK: string
	/**
	 * L​i​n​k​i​n​g​.​.​.
	 */
	NODE_LINKING: string
	/**
	 * N​a​m​e​ ​y​o​u​r​ ​i​n​t​e​r​a​c​t​i​o​n​.​.​.
	 */
	NODE_INTERACTION_PH: string
	/**
	 * L​a​b​e​l​ ​i​s​ ​r​e​q​u​i​r​e​d​ ​f​o​r​ ​t​h​i​s​ ​i​n​t​e​r​a​c​t​i​o​n
	 */
	NODE_INTERACTION_REQUIRED: string
	/**
	 * T​a​g​:​ ​N​o​t​ ​L​i​n​k​e​d
	 */
	NODE_TAG_NOT_LINKED: string
	/**
	 * U​p​d​a​t​e
	 */
	NODE_UPDATE: string
	/**
	 * L​i​n​k​ ​T​a​g
	 */
	NODE_LINK_TAG: string
	/**
	 * W​a​i​t​ ​T​a​g​.​.​.
	 */
	NODE_WAIT_TAG: string
	/**
	 * O​f​f​l​i​n​e
	 */
	NODE_OFFLINE: string
	/**
	 * N​o​ ​I​m​a​g​e
	 */
	CANVAS_NO_IMAGE: string
	/**
	 * C​l​i​c​k​ ​+​ ​d​r​a​g​ ​t​o​ ​p​a​n​ ​
​ ​C​l​i​c​k​ ​o​n​ ​a​ ​c​h​a​p​t​e​r​ ​t​o​ ​s​e​l​e​c​t​ ​i​t​ ​
​ ​S​c​r​o​l​l​ ​t​o​ ​z​o​o​m​ ​i​n​ ​
​ ​U​s​e​ ​t​h​e​ ​b​u​t​t​o​n​ ​a​b​o​v​e​ ​t​o​ ​a​d​d​ ​a​ ​n​e​w​ ​c​h​a​p​t​e​r
	 */
	CANVAS_HINT: string
	/**
	 * L​o​a​d​i​n​g​ ​s​t​o​r​y
	 */
	PLAY_LOADING_TITLE: string
	/**
	 * W​e​'​r​e​ ​g​e​t​t​i​n​g​ ​t​h​e​ ​i​n​t​e​r​a​c​t​i​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​r​e​a​d​y​ ​f​o​r​ ​y​o​u​.​.​.
	 */
	PLAY_LOADING_DESC: string
	/**
	 * S​t​o​r​y​ ​n​o​t​ ​f​o​u​n​d
	 */
	PLAY_NOT_FOUND: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	PLAY_LOADING: string
	/**
	 * T​e​x​t​ ​S​i​z​e
	 */
	SETTINGS_TEXT_SIZE: string
	/**
	 * V​o​l​u​m​e
	 */
	SETTINGS_VOLUME: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	STORY_SETTINGS: string
	/**
	 * R​e​p​l​a​y​ ​a​u​d​i​o
	 */
	STORY_REPLAY_AUDIO: string
	/**
	 * T​h​i​s​ ​i​s​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​s​t​o​r​y​.​ ​P​r​e​s​s​ ​a​n​y​ ​k​e​y​ ​t​o​ ​c​l​o​s​e​ ​t​h​e​ ​s​t​o​r​y​.
	 */
	STORY_END: string
	/**
	 * (​A​u​d​i​o​)
	 */
	STORY_OPTION_AUDIO: string
	/**
	 * S​t​o​r​y​ ​B​a​c​k​g​r​o​u​n​d
	 */
	STORY_BG_ALT: string
	/**
	 * W​h​i​s​p​e​r​ ​T​e​s​t​e​r
	 */
	TEST_TITLE: string
	/**
	 * S​c​a​n​n​e​r​ ​S​t​a​t​u​s
	 */
	TEST_SCANNER_STATUS: string
	/**
	 * A​c​t​i​v​e​ ​&​ ​P​o​l​l​i​n​g
	 */
	TEST_ACTIVE_POLLING: string
	/**
	 * H​a​r​d​w​a​r​e​ ​U​I​D
	 */
	TEST_HARDWARE_UID: string
	/**
	 * N​D​E​F​ ​C​o​n​t​e​n​t
	 */
	TEST_NDEF_CONTENT: string
	/**
	 * A​s​s​i​g​n​e​d​ ​L​a​b​e​l​s
	 */
	TEST_ASSIGNED_LABELS: string
	/**
	 * S​e​a​r​c​h​i​n​g​ ​s​t​o​r​i​e​s​.​.​.
	 */
	TEST_SEARCHING: string
	/**
	 * N​o​ ​a​c​t​i​v​e​ ​c​a​l​i​b​r​a​t​i​o​n​s​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​i​s​ ​t​a​g​ ​i​n​ ​a​n​y​ ​s​t​o​r​y​.
	 */
	TEST_NO_CALIBRATIONS: string
	/**
	 * W​h​i​s​p​e​r​ ​O​f​f​l​i​n​e
	 */
	TEST_OFFLINE: string
	/**
	 * W​a​i​t​i​n​g​ ​f​o​r​ ​T​a​g​.​.​.
	 */
	TEST_WAITING: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​I​s​s​u​e
	 */
	TEST_CONNECTION_ISSUE: string
	/**
	 * S​t​o​r​y
	 */
	TABLE_STORY: string
	/**
	 * L​a​b​e​l
	 */
	TABLE_LABEL: string
	/**
	 * S​t​a​r​t​ ​s​t​o​r​y
	 */
	PLAY_BTN: string
}

export type TranslationFunctions = {
	/**
	 * Play a story
	 */
	HOME_PLAY_STORY: () => LocalizedString
	/**
	 * Manage story
	 */
	HOME_MANAGE_STORY: () => LocalizedString
	/**
	 * Make a story
	 */
	HOME_MAKE_STORY: () => LocalizedString
	/**
	 * Play stories made by you or others!
	 */
	HOME_TOOLTIP_PLAY: () => LocalizedString
	/**
	 * Click here to edit stories!
	 */
	HOME_TOOLTIP_MANAGE: () => LocalizedString
	/**
	 * Click here to make a new story!
	 */
	HOME_TOOLTIP_MAKE: () => LocalizedString
	/**
	 * test connection
	 */
	HOME_TEST_CONNECTION: () => LocalizedString
	/**
	 * Manage My Stories
	 */
	MANAGE_TITLE: () => LocalizedString
	/**
	 * Managing stories...
	 */
	MANAGE_LOADING_TITLE: () => LocalizedString
	/**
	 * Please wait a moment, we're loading your library...
	 */
	MANAGE_LOADING_DESC: () => LocalizedString
	/**
	 * No stories found yet.
	 */
	MANAGE_EMPTY: () => LocalizedString
	/**
	 * Start by creating your first story
	 */
	MANAGE_CREATE_FIRST: () => LocalizedString
	/**
	 * Edit Story
	 */
	MANAGE_EDIT_STORY: () => LocalizedString
	/**
	 * Export Story
	 */
	MANAGE_EXPORT_STORY: () => LocalizedString
	/**
	 * Delete Story
	 */
	MANAGE_DELETE_STORY: () => LocalizedString
	/**
	 * Are you sure you want to delete "{name}"? This action cannot be undone.
	 */
	MANAGE_CONFIRM_DELETE: (arg: { name: string }) => LocalizedString
	/**
	 * Confirm Deletion
	 */
	MANAGE_CONFIRM_DELETE_TITLE: () => LocalizedString
	/**
	 * Create A New Story
	 */
	MAKE_TITLE_NEW: () => LocalizedString
	/**
	 * Edit Your Story
	 */
	MAKE_TITLE_EDIT: () => LocalizedString
	/**
	 * My Stories
	 */
	OVERVIEW_TITLE: () => LocalizedString
	/**
	 * Select a story to play
	 */
	OVERVIEW_TOOLTIP: () => LocalizedString
	/**
	 * Loading stories...
	 */
	OVERVIEW_LOADING_TITLE: () => LocalizedString
	/**
	 * Please wait a moment, we're loading your library...
	 */
	OVERVIEW_LOADING_DESC: () => LocalizedString
	/**
	 * No stories found
	 */
	OVERVIEW_EMPTY: () => LocalizedString
	/**
	 * Make your first story
	 */
	OVERVIEW_MAKE_FIRST: () => LocalizedString
	/**
	 * story image not found
	 */
	OVERVIEW_IMAGE_ALT: () => LocalizedString
	/**
	 * Edit story
	 */
	OVERVIEW_EDIT_STORY: () => LocalizedString
	/**
	 * Calibrate Tags
	 */
	OVERVIEW_CALIBRATE: () => LocalizedString
	/**
	 * Help
	 */
	HELP_TITLE: () => LocalizedString
	/**
	 * Export story
	 */
	STORY_CARD_EXPORT: () => LocalizedString
	/**
	 * Delete story
	 */
	STORY_CARD_DELETE: () => LocalizedString
	/**
	 * Delete story?
	 */
	STORY_CARD_CONFIRM_TITLE: () => LocalizedString
	/**
	 * "{name}" will be permanently deleted.
	 */
	STORY_CARD_CONFIRM_MSG: (arg: { name: string }) => LocalizedString
	/**
	 * Cancel
	 */
	STORY_CARD_CANCEL: () => LocalizedString
	/**
	 * Delete
	 */
	STORY_CARD_DELETE_BTN: () => LocalizedString
	/**
	 * No Image
	 */
	IMAGE_NO_IMAGE: () => LocalizedString
	/**
	 * Change Audio
	 */
	AUDIO_CHANGE: () => LocalizedString
	/**
	 * Upload Audio
	 */
	AUDIO_UPLOAD: () => LocalizedString
	/**
	 * Whisper Active
	 */
	NFC_ACTIVE: () => LocalizedString
	/**
	 * Whisper Error
	 */
	NFC_ERROR: () => LocalizedString
	/**
	 * Whisper Offline
	 */
	NFC_OFFLINE: () => LocalizedString
	/**
	 * Whisper is the codename for the NFC reader
	 */
	NFC_TITLE: () => LocalizedString
	/**
	 * Calibrate Story:
	 */
	CALIB_TITLE: () => LocalizedString
	/**
	 * Link your physical tags to the items in this story.
	 */
	CALIB_DESC: () => LocalizedString
	/**
	 * Unnamed Item
	 */
	CALIB_UNNAMED: () => LocalizedString
	/**
	 * Linked Tag
	 */
	CALIB_LINKED_TAG: () => LocalizedString
	/**
	 * Not calibrated
	 */
	CALIB_NOT_CALIBRATED: () => LocalizedString
	/**
	 * Scanning...
	 */
	CALIB_SCANNING: () => LocalizedString
	/**
	 * Calibrate
	 */
	CALIB_BTN: () => LocalizedString
	/**
	 * Re-calibrate
	 */
	CALIB_RECALIBRATE: () => LocalizedString
	/**
	 * Connect Whisper reader...
	 */
	CALIB_CONNECT_READER: () => LocalizedString
	/**
	 * Place tag on reader...
	 */
	CALIB_PLACE_TAG: () => LocalizedString
	/**
	 * Confirm Link
	 */
	CALIB_CONFIRM_LINK: () => LocalizedString
	/**
	 * This story has no interactive items.
	 */
	CALIB_NO_ITEMS: () => LocalizedString
	/**
	 * Done
	 */
	CALIB_DONE: () => LocalizedString
	/**
	 * Please enter a story name
	 */
	MAKE_CARD_NAME_REQUIRED: () => LocalizedString
	/**
	 * Story Name
	 */
	MAKE_CARD_NAME_LABEL: () => LocalizedString
	/**
	 * Story Title
	 */
	MAKE_CARD_NAME_PLACEHOLDER: () => LocalizedString
	/**
	 * Description
	 */
	MAKE_CARD_DESC_LABEL: () => LocalizedString
	/**
	 * Tell a bit about your story...
	 */
	MAKE_CARD_DESC_PLACEHOLDER: () => LocalizedString
	/**
	 * Update & Continue
	 */
	MAKE_CARD_UPDATE: () => LocalizedString
	/**
	 * Start Telling Your Story
	 */
	MAKE_CARD_START: () => LocalizedString
	/**
	 * Loading design environment
	 */
	CONFIG_LOADING_TITLE: () => LocalizedString
	/**
	 * Loading chapters and interactive paths...
	 */
	CONFIG_LOADING_DESC: () => LocalizedString
	/**
	 * Are you sure you want to leave? Unsaved changes will not be saved.
	 */
	CONFIG_UNSAVED_MSG: () => LocalizedString
	/**
	 * Unsaved Changes
	 */
	CONFIG_UNSAVED_TITLE: () => LocalizedString
	/**
	 * New Story
	 */
	CONFIG_NEW_STORY: () => LocalizedString
	/**
	 * Chapter
	 */
	CONFIG_CHAPTER_SINGULAR: () => LocalizedString
	/**
	 * Chapters
	 */
	CONFIG_CHAPTER_PLURAL: () => LocalizedString
	/**
	 * + Add New Chapter
	 */
	CONFIG_ADD_CHAPTER: () => LocalizedString
	/**
	 * Save Changes
	 */
	CONFIG_SAVE: () => LocalizedString
	/**
	 * Saved
	 */
	CONFIG_SAVED: () => LocalizedString
	/**
	 * Select a chapter to start editing
	 */
	NODE_SELECT_HINT: () => LocalizedString
	/**
	 * Edit Chapter
	 */
	NODE_EDIT_CHAPTER: () => LocalizedString
	/**
	 * Delete Chapter
	 */
	NODE_DELETE_CHAPTER: () => LocalizedString
	/**
	 * Chapter Title
	 */
	NODE_CHAPTER_TITLE_LABEL: () => LocalizedString
	/**
	 * Name your chapter...
	 */
	NODE_CHAPTER_TITLE_PH: () => LocalizedString
	/**
	 * Description
	 */
	NODE_DESC_LABEL: () => LocalizedString
	/**
	 * What happens in this chapter?
	 */
	NODE_DESC_PH: () => LocalizedString
	/**
	 * Illustration
	 */
	NODE_ILLUSTRATION: () => LocalizedString
	/**
	 * Narration
	 */
	NODE_NARRATION: () => LocalizedString
	/**
	 * Fail Audio (Optional)
	 */
	NODE_FAIL_AUDIO: () => LocalizedString
	/**
	 * Links & Interactions
	 */
	NODE_LINKS: () => LocalizedString
	/**
	 * + Add Link
	 */
	NODE_ADD_LINK: () => LocalizedString
	/**
	 * Linking...
	 */
	NODE_LINKING: () => LocalizedString
	/**
	 * Name your interaction...
	 */
	NODE_INTERACTION_PH: () => LocalizedString
	/**
	 * Label is required for this interaction
	 */
	NODE_INTERACTION_REQUIRED: () => LocalizedString
	/**
	 * Tag: Not Linked
	 */
	NODE_TAG_NOT_LINKED: () => LocalizedString
	/**
	 * Update
	 */
	NODE_UPDATE: () => LocalizedString
	/**
	 * Link Tag
	 */
	NODE_LINK_TAG: () => LocalizedString
	/**
	 * Wait Tag...
	 */
	NODE_WAIT_TAG: () => LocalizedString
	/**
	 * Offline
	 */
	NODE_OFFLINE: () => LocalizedString
	/**
	 * No Image
	 */
	CANVAS_NO_IMAGE: () => LocalizedString
	/**
	 * Click + drag to pan 
 Click on a chapter to select it 
 Scroll to zoom in 
 Use the button above to add a new chapter
	 */
	CANVAS_HINT: () => LocalizedString
	/**
	 * Loading story
	 */
	PLAY_LOADING_TITLE: () => LocalizedString
	/**
	 * We're getting the interactive experience ready for you...
	 */
	PLAY_LOADING_DESC: () => LocalizedString
	/**
	 * Story not found
	 */
	PLAY_NOT_FOUND: () => LocalizedString
	/**
	 * Loading...
	 */
	PLAY_LOADING: () => LocalizedString
	/**
	 * Text Size
	 */
	SETTINGS_TEXT_SIZE: () => LocalizedString
	/**
	 * Volume
	 */
	SETTINGS_VOLUME: () => LocalizedString
	/**
	 * Settings
	 */
	STORY_SETTINGS: () => LocalizedString
	/**
	 * Replay audio
	 */
	STORY_REPLAY_AUDIO: () => LocalizedString
	/**
	 * This is the end of the story. Press any key to close the story.
	 */
	STORY_END: () => LocalizedString
	/**
	 * (Audio)
	 */
	STORY_OPTION_AUDIO: () => LocalizedString
	/**
	 * Story Background
	 */
	STORY_BG_ALT: () => LocalizedString
	/**
	 * Whisper Tester
	 */
	TEST_TITLE: () => LocalizedString
	/**
	 * Scanner Status
	 */
	TEST_SCANNER_STATUS: () => LocalizedString
	/**
	 * Active & Polling
	 */
	TEST_ACTIVE_POLLING: () => LocalizedString
	/**
	 * Hardware UID
	 */
	TEST_HARDWARE_UID: () => LocalizedString
	/**
	 * NDEF Content
	 */
	TEST_NDEF_CONTENT: () => LocalizedString
	/**
	 * Assigned Labels
	 */
	TEST_ASSIGNED_LABELS: () => LocalizedString
	/**
	 * Searching stories...
	 */
	TEST_SEARCHING: () => LocalizedString
	/**
	 * No active calibrations found for this tag in any story.
	 */
	TEST_NO_CALIBRATIONS: () => LocalizedString
	/**
	 * Whisper Offline
	 */
	TEST_OFFLINE: () => LocalizedString
	/**
	 * Waiting for Tag...
	 */
	TEST_WAITING: () => LocalizedString
	/**
	 * Connection Issue
	 */
	TEST_CONNECTION_ISSUE: () => LocalizedString
	/**
	 * Story
	 */
	TABLE_STORY: () => LocalizedString
	/**
	 * Label
	 */
	TABLE_LABEL: () => LocalizedString
	/**
	 * Start story
	 */
	PLAY_BTN: () => LocalizedString
}

export type Formatters = {}
